FROM openjdk:17-oracle
VOLUME /tmp
ARG REGION_ARG=eu-central-1
ARG ACCESS_ARG
ARG SECRET_ARG
ENV AWS_REGION=$REGION_ARG
ENV AWS_ACCESS_KEY=$ACCESS_ARG
ENV AWS_SECRET_KEY=$SECRET_ARG
COPY target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]